### ISSUE TITLE
Failed to parse lesson pages

### ISSUE THREAD

**Issue by edwinharly** [rohmanhm/new-egghead-downloader#10]
I'm trying to download this [lesson](https://egghead.io/courses/build-a-react-app-with-redux) with this command `ehd -c https://egghead.io/courses/build-a-react-app-with-redux`, the error output is `Error: Failed to parse the following lesson pages: 'https://egghead.io/lessons/react . . . They might be for pro subscribers only
Error: no video found!`

And it's not for pro subscribers only for now as I've tried to play the videos

**Comment by dasiekjs** [comment]
When i Try to login (using -e -p) i got output

`Authenticated!
The URL is a playlist or series
Found 26 lessons
Error: fetching the url 'https://egghead.io/courses/build-a-react-app-with-redux' failed!`

**Comment by rohmanhm** [comment]
Maybe this can help.
https://github.com/produk/new-egghead-downloader/issues/12
