### ISSUE TITLE
Not able to download any courses

### ISSUE THREAD

**Issue by ashking** [rohmanhm/new-egghead-downloader#11]
Hi there, 

When I try to download a course, let's say https://egghead.io/courses/develop-basic-web-apps-with-vue-js, I end up with the following error:

```
Authenticated!
The URL is a playlist or series
Found 0 lesson
Error: fetching the url 'https://egghead.io/courses/develop-basic-web-apps-with-vue-js' failed!
```

@rohmanhm , can you fix/update the scripts to download courses? thanks!

**Comment by rohmanhm** [comment]
It seems egghead made changes to their website again,

**Comment by ashking** [comment]
Yup, 

time to update the scripts? :)

**Comment by elodszopos** [comment]
Would love to see this fixed!

**Comment by rohmanhm** [comment]
Any PR welcome. I got busy right now 😞
