### ISSUE TITLE
Still failed to download even after update to version 0.2.5

### ISSUE THREAD

**Issue by edwinharly** [rohmanhm/new-egghead-downloader#12]
`ehd -c https://egghead.io/lessons/vue-js-create-a-vuex-store-using-typescript`

gives me this error

`The URL is a lesson`
`Error: failed to parse the lesson page 'https://egghead.io/lessons/vue-js-create-a-vuex-store-using-typescript'}`

**Comment by edwinharly** [comment]
I've also make sure that this lesson is available for free users by the time I try to download it. They might limit it for pro subscribers only in the future just like other lessons

**Comment by rohmanhm** [comment]
You need to authenticated!
provide your email and password
```bash
❯ ehd -e my@email.com -p mypassword https://egghead.io/lessons/vue-js-create-a-vuex-store-using-typescript     
Authenticated!
The URL is a lesson
Found 1 video
Downloading video 1 out of 1: '01-egghead-vue-js-create-a-vuex-store-using-typesDownloading video 1 out of 1: '01-egghead-vue-js-create-a-vuex-store-using-typesDownloading video 1 out of 1: '01-egghead-vue-js-create-a-vuex-store-using-typescript.mp4'..^C
```

**Comment by edwinharly** [comment]
`Authenticated!`
`The URL is a lesson`
`Error: fetching the url 'https://egghead.io/lessons/vue-js-create-a-vuex-store-using-typescript' failed!`

Still error, I'm really out of idea this time, I'm using node v6.11.2 & npm v5.4.2

**Comment by pleopardi** [comment]
Same problem, not working even when authenticated.
Free course: https://egghead.io/courses/leverage-new-features-of-react-16

Logs:

> Authenticated!
The URL is a playlist or series
Found 6 lessons
Error: fetching the url 'https://egghead.io/courses/leverage-new-features-of-react-16' failed!

**Comment by rohmanhm** [comment]
To download videos, you need a PRO account!

**Comment by pleopardi** [comment]
I was able to download free courses with a free account until a couple of weeks ago. How is that possible?

**Comment by gggauravgandhi** [comment]
Video page structure is changed, so it won't any more.
