### ISSUE TITLE
No videos found!

### ISSUE THREAD

**Issue by a-eid** [rohmanhm/new-egghead-downloader#14]
I getting the following error

![screen shot 2017-11-22 at 21 49 20](https://user-images.githubusercontent.com/19273413/33144753-1eb43bdc-cfcf-11e7-8024-10b92ab3bc3f.png)

**Comment by mateuszzw** [comment]
Same here - no videos found on every course
UPDATE: it's only for courses (playlists) - for single videos it's working fine

**Comment by rohmanhm** [comment]
Hi guys, I'm sorry for late reply.
I think it causes by egghead update their HTML structure again.

Any PR welcome for the update

**Comment by mateuszzw** [comment]
Hi @rohmanhm 
In the meantime, I wrote a very simple snippet for retrieving links of single lessons from full course page e.g.  https://egghead.io/courses/start-learning-react

```
jQuery.each(jQuery('.mb4.br2-ns.overflow-hidden-ns').find('.mb2.mb0-ns.base.no-underline.db.pl0.tl.f4.fw5.avenir.pointer.lh-title.lh-copy-ns.relative'), function(index, video){
  console.log('ehd -e email -p password ' + video.href + ' -f');
});
```
I managed to download all course's lessons separately using this snippet.
I hope this helps.
