### ISSUE TITLE
Downloaded Files Corrupted?

### ISSUE THREAD

**Issue by NathanielGiron** [rohmanhm/new-egghead-downloader#4]
Hi,

I am a free user and thinking of upgrading to PRO but when I tried downloading a free series, it looks like the downloaded files are corrupted? Each video is only like 9 bytes btw.

**Comment by rohmanhm** [comment]
Hm, it looks weird. I've never get that errors.
It might your internet connection.
have you tried to re-download the files?

```bash
ehd -e email@myemail.com -p mypassword https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx manage-complex-state-in-react-apps-with-mobx -f
```

This may be the same issue related #1

**Comment by NathanielGiron** [comment]
@rohmanhm Thank you for the swift response! I tried that command and now I am getting this error:
 
Authenticated!
The URL is a playlist or series
Found 9 lessons
Error: fetching the url 'https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx' failed!

**Comment by rohmanhm** [comment]
You must have PRO account to download https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx course

**Comment by NathanielGiron** [comment]
I see. How about the free courses? I still need to upgrade to PRO to be able to download a free course, correct?

**Comment by rohmanhm** [comment]
With PRO account you can download both of them.
