### ISSUE TITLE
Videos are downloaded in low quality

### ISSUE THREAD

**Issue by selrond** [rohmanhm/new-egghead-downloader#5]
I've noticed that downloaded videos are of quite low quality—lower than those on the egghead.io site.

**Comment by rohmanhm** [comment]
Have you signed in? Are you in a good network connection?

Sometimes it happen because network connection is too bad. Like Youtube, it will download low version depend on your connection

**Comment by selrond** [comment]
@rohmanhm I indeed have a great connection. I'm not signed in however, it's a free, publicly available [course](https://egghead.io/courses/get-started-using-webassembly-wasm) (as of now)

**Comment by rohmanhm** [comment]
I can't reproduce this issue, with or without signed. 😢

Try to provide your username and password, if it's works maybe egghead add limitation for unsigned account.

**Comment by selrond** [comment]
@rohmanhm I use
`ehd -c -f https://egghead.io/courses/get-started-using-webassembly-wasm` and get 640x360 videos

**Comment by rohmanhm** [comment]
Try to provide your username and password.
Example: https://github.com/rohmanhm/new-egghead-downloader/issues/1#issuecomment-301354767

Is it still get 640x360 videos?

**Comment by selrond** [comment]
It failed...
Output:
```
Authenticated!
The URL is a playlist or series
Found 15 lessons
Error: fetching the url 'https://egghead.io/courses/get-started-using-webassembly-wasm' failed!
```

**Comment by rohmanhm** [comment]
![image](https://user-images.githubusercontent.com/7524911/26955959-a94548c2-4ce4-11e7-9574-fe7e90ae0714.png)

You need PRO account to download videos.

I just save egghead from the hassle of DMCA filing
