### ISSUE TITLE
How does one download playlists?

### ISSUE THREAD

**Issue by krokofant** [rohmanhm/new-egghead-downloader#6]
It seems very unclear to me. I only manage to download a single video at a time.

**Comment by rohmanhm** [comment]
1. Just search courses/playlist you want to download. eg: `https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx manage-complex-state-in-react-apps-with-mobx`
2. Copy courses or playlist URL to your clipboard.
3. Run with `ehd`. 
   Example
  ```bash
  ehd -e email@myemail.com -p mypassword https://egghead.io/courses/manage-complex-state-in-
  react-apps-with-mobx manage-complex-state-in-react-apps-with-mobx
  ```
4. It will download all courses you want to download.

May I ask, which playlist you want to downoad?

**Comment by krokofant** [comment]
https://egghead.io/courses/up-and-running-with-preact
or
https://egghead.io/lessons/javascript-install-development-tools-for-preact

Tried without login.

**Comment by rohmanhm** [comment]
Without login?
That's the problem is.

https://github.com/rohmanhm/new-egghead-downloader/issues/5#issuecomment-307263001

**Comment by krokofant** [comment]
@rohmanhm Perhaps this should be mentioned in the README then?

**Comment by rohmanhm** [comment]
You right, feel free if you want to open PR for this 🙂

**Comment by mikedevita** [comment]
@rohmanhm as an FYI egghead has taken down a few other downloader libraries with DMCA requests. @SimonSelg's lib is no longer available because of this.
