### ISSUE TITLE
add output director option `-o` 

### ISSUE THREAD

**Issue by a-eid** [rohmanhm/new-egghead-downloader#7]
add output director option `-o`

**Comment by rohmanhm** [comment]
For now you can specified output directory without `-o` option. Why do you still need to have `-o` option?

**Comment by a-eid** [comment]
I didn't know I can do that ?
How to do that ?

**Comment by rohmanhm** [comment]
Take a look some example how to download with **ehd**
```bash
ehd -e email@myemail.com -p mypassword https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx CustomDirectoryDownload
```

`CustomDirectoryDownload` is directory name you specified to.

**Comment by rohmanhm** [comment]
I'll close this issue since no longer active yet. Thanks for contribution.
Feel free to reopen it anytime. 🙂
