### ISSUE TITLE
Should we fix the app?

### ISSUE THREAD

**Issue by xamgore** [rohmanhm/new-egghead-downloader#9]
Hello, @rohmanhm. Seems that _ehd_ is broken, cause the egghead has changed the pages structure. I can make a pull request fixing the issue, but the problem is that it will be possible to download _all_ videos, even if you don't have a pro account. Is it _morally_ ok?

Also, it is possible now to get a link to a github repository and transcript. I think it is a good idea to store them with videos.

**Comment by rohmanhm** [comment]
Wow, sounds cool @xamgore
Let's give it a try

**Comment by a-eid** [comment]
any updates coming soon ? @xamgore

**Comment by rohmanhm** [comment]
I'm work on it. Sorry lately I'm little busy.

**Comment by rohmanhm** [comment]
Published `0.2.2`

**Comment by a-eid** [comment]
Issue still persist .

**Comment by rohmanhm** [comment]
What is the issue? It's worked for me.

**Comment by re8260** [comment]
Error with installation v0.2.2

```
>npm install -g ehd
npm ERR! path /usr/local/lib/node_modules/ehd/dist/app.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ehd/dist/app.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by AndreGCRamos** [comment]
I get the same error message as @re8260 when trying to install via NPM, but if I clone and run with `babel-node src/app.js ...` it runs the script, but still throws an error `(...) Error: no video found!`

**Comment by PavloPoliakov** [comment]
Have the same issue :(

And in case I cloned and built the application, I have the next issue:
![image](https://user-images.githubusercontent.com/839290/28491406-1c9a9e34-6ef1-11e7-9dbc-93de9b169856.png)

**Comment by rohmanhm** [comment]
Fixed https://github.com/rohmanhm/new-egghead-downloader/commit/603a67ea953f58d4e6e148b0dc64793e4f7a7782 **v0.2.3**
